### PR TITLE
deserialize ValueOut in ValueIn

### PR DESCRIPTION
**Pull request by juliavi**

### CODE REVIEW

**Comment by juliavi** [comment]
This isn't a real conflict. 
That's a pull request across repo's so that's how it's displayed.

**Comment by BrunoFreitasgit** [comment]
What is the argument for the change? For what I know, the object ValueOut (vout) inside of ValueIn (vin) that returns from the getrawtransaction is a int. https://github.com/neo-project/docs/blob/master/en-us/node/api/getrawtransaction.md

**Comment by BrunoFreitasgit** [comment]
can I close this pr @AshRolls ?

**Comment by BrunoFreitasgit** [comment]
@juliavi how does these new changes relate to the PR? And what are the problems fixed with the implementation of diferent interfaces for each api call?

**Comment by BrunoFreitasgit** [comment]
No further details were given, so I'm closing this PR

**Pull request closed without merging**
